# Generated by Django 4.2.16 on 2024-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='password',
            field=models.CharField(default=True, max_length=8),
        ),
    ]
